[CmdletBinding()]
param([switch]$InstallCodex,[switch]$LoginCodex,[switch]$GlobalPointers,[switch]$SkipSelfTest)
$ErrorActionPreference='Stop';$root=Split-Path -Parent (Split-Path -Parent $PSScriptRoot);$checks=@()
function Add([string]$id,[string]$status,[string]$message){$script:checks+=[pscustomobject]@{id=$id;status=$status;message=$message}}
foreach($cmd in @('git','powershell','python','wsl')){$found=Get-Command $cmd -ErrorAction SilentlyContinue;Add "command:$cmd" $(if($found){'PASS'}else{'FAIL'}) $(if($found){$found.Source}else{'missing'})}
$wslHome=(wsl -d Ubuntu -- printenv HOME|Out-String).Trim();$codexWsl="$wslHome/.local/bin/codex";$wslPath="$wslHome/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
if($InstallCodex){$rootWsl="/mnt/$($root.Substring(0,1).ToLowerInvariant())/$($root.Substring(3).Replace('\','/'))";wsl -d Ubuntu -- bash "$rootWsl/Setup/bootstrap/install-codex-wsl.sh"}
$version=(wsl -d Ubuntu -- env "PATH=$wslPath" $codexWsl --version 2>&1|Out-String).Trim();Add 'codex-wsl' $(if($LASTEXITCODE -eq 0 -and $version -match 'codex-cli'){'PASS'}else{'FAIL'}) $version
if($LoginCodex){wsl -d Ubuntu -- env "PATH=$wslPath" $codexWsl login --device-auth}
$previousErrorPreference=$ErrorActionPreference;$ErrorActionPreference='Continue';wsl -d Ubuntu -- env "PATH=$wslPath" $codexWsl login status 2>&1|Out-Null;$loginExit=$LASTEXITCODE;$ErrorActionPreference=$previousErrorPreference;$login=if($loginExit -eq 0){'Logged in'}else{'Not logged in'};Add 'codex-login' $(if($loginExit -eq 0){'PASS'}else{'WARN'}) $login
if($GlobalPointers){& powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $root 'tools/init.ps1') -Global|Out-Null}else{& powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $root 'tools/init.ps1') -TargetRepo $root|Out-Null};Add 'repo-pointers' 'PASS' $(if($GlobalPointers){'repository and global pointers refreshed'}else{'repository pointers refreshed'})
$isolationReport=Join-Path $root 'Evals/local/isolation-proof.json';& powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $root 'Evals/test-wsl-isolation.ps1') -OutputPath $isolationReport|Out-Null;$proof=Get-Content -Raw $isolationReport|ConvertFrom-Json;Add 'wsl-isolation' $(if($proof.passed){'PASS'}else{'FAIL'}) $proof.type
if(-not $SkipSelfTest){$gate=& powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $root 'tools/release-gate.ps1') -Mode infrastructure|ConvertFrom-Json;Add 'infrastructure-gate' $(if($gate.passed){'PASS'}else{'FAIL'}) "$($gate.checks_passed)/$($gate.checks.Count)"}
$provider=[ordered]@{schema_version=1;generated_at=[datetimeoffset]::Now.ToString('o');providers=@([ordered]@{id='codex-wsl';adapter='Evals/adapters/providers/invoke-codex-wsl.ps1';version=$version;authenticated=($loginExit -eq 0);isolation='wsl-user-mount-namespace';model='set per experiment from current provider catalog';effort='set per experiment'})};$provider|ConvertTo-Json -Depth 8|Set-Content -Encoding UTF8 (Join-Path $root 'Evals/local/provider-settings.json')
$fail=@($checks|Where-Object status -eq 'FAIL').Count;$result=[ordered]@{schema_version=1;root=$root;core_ready=($fail -eq 0);benchmark_ready=($fail -eq 0 -and $loginExit -eq 0);failures=$fail;checks=$checks;next_action=if($loginExit -ne 0){'Run setup.ps1 -LoginCodex, then rerun setup.'}elseif($fail){'Resolve failed checks and rerun setup.'}else{'Environment is ready for full-gate fixture work.'}};$result|ConvertTo-Json -Depth 8|Set-Content -Encoding UTF8 (Join-Path $root 'Evals/local/setup-status.json');$result|ConvertTo-Json -Depth 8;if($fail){exit 1}
